name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  uuid: ^4.5.1
  lucide_icons: ^0.257.0
  cached_network_image: ^3.4.1
  dotted_border: ^2.0.0
  shared_preferences: ^2.0.15  # Ensure this is added
  path_provider: ^2.0.11
  provider: ^6.1.2
  expandable: ^5.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  carousel_slider: ^5.0.0
  file_picker: ^9.2.3  # Dernière version stable

file_picker:
  git:
    url: https://github.com/miguelpruivo/flutter_file_picker
    ref: master
    path: file_picker


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  
    - assets/logo.png
    - assets/logo2.png
    - assets/canvap.png
    - assets/chickenb.png
    - assets/chickenb2.png
    - assets/background.png
    - assets/bmipict.png
    - assets/thon.png
    - assets/Egg.png
    - assets/rice.png
    - assets/as.jpg
    - assets/chickenwings.jpg
    - assets/fish.jpg
    - assets/fill.png
    - assets/oats.png
    - assets/fill3.png
    - assets/oil.png
    - assets/dates.png
    - assets/chickpeas.png
    - assets/couscous.png
    - assets/potatoes.png
    - assets/tomatoes.png
    - assets/onions.png
    - assets/garlic.png
    - assets/carrots.png
    - assets/eggs.png
    - assets/beef.png
    - assets/mintleaves.png
    - assets/greenpeas.jpg
    - assets/zucchini.png
    - assets/yugort.png
  
  
  fonts:
    - family: Lobster
      fonts:
        - asset: Lobster/Lobster-Regular.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: Roboto/Roboto-Bold.ttf
          weight: 700

    - family: MyFlutterApp
      fonts:
        - asset: icons/MyFlutterApp.ttf

    